//> using scala "3.6.2"
//> using resourceDir ./resources
//> using dep "dev.zio::zio:2.1.14"
//> using dep "dev.zio::zio-config::4.0.3"
//> using dep "dev.zio::zio-config-magnolia::4.0.3"
//> using dep "dev.zio::zio-config-typesafe::4.0.3"
//> using dep "dev.zio::zio-logging::2.4.0"
//> using dep "dev.zio::zio-logging-slf4j2::2.4.0"
//> using dep "dev.zio::zio-metrics-connectors-datadog::2.3.1"
//> using dep "dev.zio::zio-test:2.1.14"
//> using dep "dev.zio::zio-test-sbt:2.1.14"
//> using testFramework zio.test.sbt.ZTestFramework
